"""empty message

Revision ID: 93feec55d93c
Revises: 
Create Date: 2019-01-15 20:26:15.266039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93feec55d93c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('Title', sa.String(length=40), nullable=True))
    op.add_column('movies', sa.Column('category', sa.String(length=40), nullable=False))
    op.add_column('movies', sa.Column('desc', sa.String(length=255), nullable=False))
    op.drop_column('movies', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('title', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('movies', 'desc')
    op.drop_column('movies', 'category')
    op.drop_column('movies', 'Title')
    # ### end Alembic commands ###
